### ISSUE TITLE
Describe how messages are delimited

### ISSUE THREAD

**Issue by nex3** [sass/sass-embedded-protocol#13]
Protocol buffers are not self-delimiting, so if we want to communicate over a stream that's not inherently packet-based (which we do, since we plan to use stdin/stdout), we'll need a scheme for indicating which bytes belong to which message. [The "Techniques" page](https://developers.google.com/protocol-buffers/docs/techniques#streaming) of the protobuf documentation suggests writing the message length before the message, which seems like as good a solution as any.

**Comment by strychnide** [comment]
I don't get if it means sending two message (one "fixed length" and one the actual message) or parsing one message up to the "length" field and then parse the remaining part.
Either way, seems more complicated than a delimiter of some sort (not really part of the protocol, but could be negotiated like I was suggesting in #14

**Comment by nex3** [comment]
> I don't get if it means sending two message (one "fixed length" and one the actual message) or parsing one message up to the "length" field and then parse the remaining part.

I don't think the protocol buffer binary format has a way of sending fixed-length messages, so we'd probably want to do something out-of-band, like a 64-bit integer before each message.

> Either way, seems more complicated than a delimiter of some sort

I'm not sure what we could use as a delimiter... as far as I know, any byte sequence could show up in a binary-encoded protocol buffer.

**Comment by strychnide** [comment]
Well, multipart/form-data uses the same idea and is considered solid, so I guess a sufficiently long/randomized string won't really be a problem. Besides the whole stack we're building this for stands atop of a long pile of "good enough randomness", lol.
