### ISSUE TITLE
Add protocol-level error handling

### ISSUE THREAD

**Issue by nex3** [sass/sass-embedded-protocol#2]
The protocol needs a way for one endpoint to signal to the other that its request was invalid. I think it's generally a good idea to do something like JSON-RPC 2.0's [error messages](https://www.jsonrpc.org/specification#error_object).

**Comment by strychnide** [comment]
Couldn't we just use the LogEvent messages for this?

**Comment by nex3** [comment]
`LogEvent` represents non-fatal messages, so that there may be many `LogEvent`s for each individual compilation. What this is tracking is a way of handling a message that's invalid on the protocol level (such as a `LogEvent` with a `SourceSpan` but no `SourceLocation`s). I guess we probably need a separate issue to track a failed compilation.

**Comment by strychnide** [comment]
Clear, thanks for clarifying and editing the title.
